name: CI

on: 
  # Replace with your main branch if needed
  push:
    branches:
      - develop
      - main
  pull_request: 
    branches:
      - develop
      - main

jobs:

  runTests:

    name: Run Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      #- name: Cache Library
       #  uses: actions/cache@v2
        # with:
         #  path: Library
          # key: Library

      - name: Run tests and generate Coverage XML report
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          unityVersion: 2021.3.15f1
          testMode: All
          customParameters: -debugCodeOptimization -enableCodeCoverage -coverageResultsPath ./coverage-results -coverageOptions generateAdditionalMetrics

     # Return License
      # - name: Return license
       #  uses: game-ci/unity-return-license@v2
        # if: always()
        
      - name: Upload XML report to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: PlayMode
          flags: automated
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage-results/**/*.xml
